services:
  - type: web
    name: roseberyunited-stonks
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 30 --bind 0.0.0.0:$PORT
